# -*- coding: utf-8 -*-
"""Final_Project_MRMB_ANOP330

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u6kmqopmG3ovQmFbffU4Bn8yr9HQA3Fp
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, cross_val_score, GridSearchCV
from sklearn.linear_model import LinearRegression, Lasso, LassoCV
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier
from sklearn.preprocessing import StandardScaler, PolynomialFeatures
from sklearn.metrics import (
    accuracy_score, recall_score, precision_score, f1_score,
    confusion_matrix, ConfusionMatrixDisplay, classification_report,
    roc_curve, roc_auc_score, mean_squared_error, mean_absolute_error, r2_score
)
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

pd.set_option("display.max_columns", 20)
pd.set_option("display.max_rows", 20)

"""## Part 1. Clean Data"""

# load in data
# Historical data:
# https://raw.githubusercontent.com/MattDBailey/ANOP330/refs/heads/main/Data/BucknellLendingClubHistoricalData.csv

# Current Applications:
# https://raw.githubusercontent.com/MattDBailey/ANOP330/refs/heads/main/Data/BucknellLendingClubCurrentData.csv


final_df = pd.read_csv('https://raw.githubusercontent.com/MattDBailey/ANOP330/refs/heads/main/Data/BucknellLendingClubHistoricalData.csv')

print(f"Dataset shape: {final_df.shape}")
final_df.head()

# Quick EDA report — same function as the Decision Tree notebook
def report(df):
    col, d_type, uniques, n_uniques, n_nulls, size = [], [], [], [], [], []
    for i in df.columns:
        col.append(i)
        d_type.append(df[i].dtypes)
        uniques.append(df[i].unique()[:5])
        n_uniques.append(df[i].nunique())
        n_nulls.append(df[i].isnull().sum())
        size.append(df[i].size)
    return pd.DataFrame({'Column': col, 'd_type': d_type, 'unique_sample': uniques,
                         'n_uniques': n_uniques, 'n_nulls': n_nulls, 'size': size})

pd.set_option('display.max_rows', 50)
report(final_df)

final_df['emp_length'] = final_df['emp_length'].fillna(final_df['emp_length'].mode()[0])
final_df = final_df[final_df['dti'] < 999].copy()
report(final_df)

"""### Data Visualization"""

from typing_extensions import final
# show the def rate overall
def_rate = final_df['loan_status'].value_counts(normalize=True) * 100
print("Charge Off Rate: {:.2f}%".format(def_rate[1]))

# def count plot using relative frequency
fig,ax = plt.subplots(nrows=1, ncols=1, figsize=(8,5))

sns.countplot(x='loan_status', data=final_df, palette=['#003865', '#E87722'], ax=ax)
plt.title('Customer Default Distribution', fontsize=14)

plt.show()

plt.figure(figsize=(10, 6))
sns.histplot(final_df['ret_PESS'], kde=True, bins=50)
plt.title('Distribution of ret_PESS')
plt.xlabel('ret_PESS Value')
plt.ylabel('Frequency')
plt.grid(axis='y', alpha=0.75)
plt.show()

plt.figure(figsize=(10, 6))
sns.histplot(final_df['annual_inc'], kde=True, bins=50)
plt.title('Distribution of Annual Income')
plt.xlabel('Annual Income')
plt.ylabel('Frequency')
plt.grid(axis='y', alpha=0.75)
plt.show()

print("--- ret_PESS Analysis by Loan Status ---")

# Calculate median ret_PESS for each loan_status
median_ret_pess = final_df.groupby('loan_status')['ret_PESS'].median()
print("\nMedian ret_PESS:")
print(median_ret_pess)

# Calculate mean ret_PESS for each loan_status
mean_ret_pess = final_df.groupby('loan_status')['ret_PESS'].mean()
print("\nMean ret_PESS:")
print(mean_ret_pess)

# Visualization: Box plot to show distribution
plt.figure(figsize=(10, 6))
sns.boxplot(x='loan_status', y='ret_PESS', data=final_df, palette='viridis')
plt.title('Distribution of ret_PESS by Loan Status', fontsize=16)
plt.xlabel('Loan Status', fontsize=12)
plt.ylabel('ret_PESS', fontsize=12)
plt.grid(axis='y', alpha=0.75)
plt.show()

# Visualization: Bar plot for Mean ret_PESS
plt.figure(figsize=(8, 5))
sns.barplot(x=mean_ret_pess.index, y=mean_ret_pess.values, palette='coolwarm')
plt.title('Average ret_PESS by Loan Status', fontsize=16)
plt.xlabel('Loan Status', fontsize=12)
plt.ylabel('Average ret_PESS', fontsize=12)
# Add values on top of bars
for index, value in enumerate(mean_ret_pess.values):
    plt.text(index, value + 0.1, f'{value:.2f}', color='black', ha='center')
plt.grid(axis='y', alpha=0.75)
plt.show()

# Set predictors
# Set targets
predictors = ['loan_amnt', 'term_num', 'int_rate', 'grade', 'emp_length', 'home_ownership', 'annual_inc',
              'verification_status', 'purpose', 'dti', 'fico_range_high', 'open_acc', 'pub_rec', 'delinq_2yrs',
              'revol_bal', 'revol_util']

# predictors_nb = ['loan_amnt', 'term_num', 'emp_length', 'home_ownership', 'annual_inc',
#               'purpose', 'dti', 'fico_range_high', 'open_acc', 'pub_rec', 'delinq_2yrs',
#               'revol_bal', 'revol_util']
outcome_status = 'loan_status'
outcome_return = 'ret_PESS'

X = final_df[predictors]
y_status = (final_df[outcome_status] == 'Charged Off').astype(int)
y_return = final_df[outcome_return]

print(f"Predictors ({X.shape[1]} features):")
print(X.columns.tolist())
print(f"\nTarget 1: {outcome_status}")
print(f"\nTarget 2: {outcome_return}")

print("Data Types in X:")
print(X.dtypes.value_counts())
print("\nCategorical columns:")
categorical_cols = X.select_dtypes(include=['object']).columns.tolist()
print(categorical_cols)
print("\nNumerical columns:")
numerical_cols = X.select_dtypes(include=['number']).columns.tolist()
print(numerical_cols)

# Apply log transformation to annual_inc in the original X DataFrame
X['annual_inc_log'] = np.log1p(X['annual_inc'])

# Drop the original annual_inc column if you want to use only the transformed one
X = X.drop('annual_inc', axis=1)

print("Log transformation applied to 'annual_inc'. New column 'annual_inc_log' created.")
print(f"X shape after transformation: {X.shape}")
print(X.head())

# Encode dummy variables
X_e = pd.get_dummies(X, columns=categorical_cols, drop_first=True)
print(f"Original features: {X.shape[1]} columns")
print(f"After encoding:    {X_e.shape[1]} columns")
print(f"\nNew columns added: {X_e.shape[1] - len(numerical_cols)}")

# Correlation heatmap — helps identify strong predictors and multicollinearity
corr = pd.concat([X_e, y_status], axis=1).corr()

fig, ax = plt.subplots(figsize=(12, 8))
sns.heatmap(corr, annot=False, fmt=".2f", cmap="RdBu", center=0, ax=ax, annot_kws={"size": 9})
ax.set_title('Loans Status — Feature Correlation Matrix', fontsize=14)
plt.tight_layout()
plt.show()

# Correlation heatmap — helps identify strong predictors and multicollinearity
corr = pd.concat([X_e, y_return], axis=1).corr()

fig, ax = plt.subplots(figsize=(12, 8))
sns.heatmap(corr, annot=False, fmt=".2f", cmap="RdBu", center=0, ax=ax, annot_kws={"size": 9})
ax.set_title('Loans Return — Feature Correlation Matrix', fontsize=14)
plt.tight_layout()
plt.show()

# Train-Test Split (80% Train, 20% Test)
# Use the exact same random_state so the rows line up for both tasks
X_train, X_test, y_class_train, y_class_test, y_reg_train, y_reg_test = train_test_split(
    X_e, y_status, y_return, test_size=0.2, random_state=42, stratify=y_status
)

# Initialize scaler
scaler = StandardScaler()

# Fit ONLY on training data, then transform both train and test
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

"""## Part 2. Models

### DecisionTreeClassifier
"""

# 1. Define the grid of hyperparameters to test
# We cap max_depth at 7 so the tree remains visually interpretable for the client
param_grid = {
    'max_depth': [3, 5, 7, 10],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [ 5, 7, 10, 15],
    'criterion': ['gini', 'entropy']
}

# 2. Initialize the base model
dtc_base = DecisionTreeClassifier(random_state=42)

# 3. Setup GridSearchCV
# cv=5 means 5-fold cross-validation
# scoring='roc_auc' ensures we build the best model for imbalanced risk
# n_jobs=-1 tells the computer to use all available processors to speed this up
grid_search = GridSearchCV(estimator=dtc_base,
                           param_grid=param_grid,
                           cv=5,
                           scoring='roc_auc',
                           verbose=1,
                           n_jobs=-1)

print("GridSearchCV successfully initialized!")

# 1. Run the Grid Search (This might take a minute depending on your computer's speed)
grid_search.fit(X_train, y_class_train)

# 2. Extract the best model found during the search
best_dtc_model = grid_search.best_estimator_

# 3. Display the winning parameters to the client
print("--- Grid Search Complete ---")
print("Best Hyperparameters Found:")
for param, value in grid_search.best_params_.items():
    print(f" - {param}: {value}")

print(f"\nBest Cross-Validation ROC-AUC Score: {grid_search.best_score_:.3f}")

# Calculate training accuracy
y_pred_train = best_dtc_model.predict(X_train)
train_accuracy = accuracy_score(y_class_train, y_pred_train)
print(f"Train Accuracy Score: {train_accuracy:.3f}")

from sklearn.metrics import brier_score_loss, confusion_matrix, f1_score, accuracy_score
# Generate predictions using the optimally tuned model
y_pred_class_best = best_dtc_model.predict(X_test)
y_pred_proba_best = best_dtc_model.predict_proba(X_test)[:, 1]

# Calculate final test metrics
test_auc = roc_auc_score(y_class_test, y_pred_proba_best)
test_brier = brier_score_loss(y_class_test, y_pred_proba_best)
test_accuracy = accuracy_score(y_class_test, y_pred_class_best)

# Calculate Confusion Matrix and F1 Score
cm = confusion_matrix(y_class_test, y_pred_class_best)
f1 = f1_score(y_class_test, y_pred_class_best)

print("--- Final Model Performance on Unseen Test Data ---")
print(f"Test AUC-ROC Score: {test_auc:.3f}")
print(f"Test Brier Score:   {test_brier:.3f}")
print(f"Test F1 Score:      {f1:.3f}")
print(f"Test Accuracy Score: {test_accuracy:.3f}\n")

print("Confusion Matrix:")
print(cm)
print("\nClassification Report:")
print(classification_report(y_class_test, y_pred_class_best))

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay, accuracy_score, precision_score, recall_score, f1_score
import matplotlib.pyplot as plt

# Generate the confusion matrix
cm = confusion_matrix(y_class_test, y_pred_class_best)

# Create a ConfusionMatrixDisplay object
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=['Fully Paid (0)', 'Charged Off (1)'])

# Plot the confusion matrix
fig, ax = plt.subplots(figsize=(8, 6))
disp.plot(cmap='Blues', ax=ax, values_format='d')

plt.title('Confusion Matrix for Decision Tree Classifier', fontsize=16, pad=15)
plt.xlabel('Predicted Label', fontsize=12)
plt.ylabel('True Label', fontsize=12)
plt.show()

# Calculate all performance metrics
TN, FP, FN, TP = cm.ravel()

accuracy = accuracy_score(y_class_test, y_pred_class_best)
precision = precision_score(y_class_test, y_pred_class_best, zero_division=0)
recall = recall_score(y_class_test, y_pred_class_best, zero_division=0)
f1 = f1_score(y_class_test, y_pred_class_best, zero_division=0)
specificity = TN / (TN + FP) if (TN + FP) != 0 else 0
fpr = FP / (FP + TN) if (FP + TN) != 0 else 0

print("\n--- Detailed Performance Metrics ---")
print(f"Accuracy:    {accuracy:.4f}")
print(f"Precision:   {precision:.4f}")
print(f"Recall:      {recall:.4f}")
print(f"F1 Score:    {f1:.4f}")
print(f"Specificity: {specificity:.4f}")
print(f"FPR:         {fpr:.4f}")

import matplotlib.pyplot as plt
import seaborn as sns

# Data for plotting
metrics = ['Train Accuracy', 'Test Accuracy']
accuracy_values = [train_accuracy, test_accuracy]

plt.figure(figsize=(8, 5))
sns.barplot(x=metrics, y=accuracy_values, palette='viridis')
plt.ylim(0.0, 1.0) # Accuracy ranges from 0 to 1
plt.title('Train vs. Test Accuracy of Decision Tree Classifier')
plt.ylabel('Accuracy Score')

# Add accuracy values on top of the bars
for index, value in enumerate(accuracy_values):
    plt.text(index, value + 0.02, f'{value:.3f}', color='black', ha="center")

plt.grid(axis='y', alpha=0.75)
plt.show()

# Calculate False Positive Rate (FPR) and True Positive Rate (TPR) for the curve
fpr, tpr, thresholds = roc_curve(y_class_test, y_pred_proba_best)

# Create the plot
plt.figure(figsize=(8, 6))
plt.plot(fpr, tpr, color='blue', lw=2, label=f'Optimized Decision Tree (AUC = {test_auc:.3f})')
plt.plot([0, 1], [0, 1], color='gray', lw=2, linestyle='--', label='Random Guessing (AUC = 0.500)')

# Formatting the chart for the client
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('False Positive Rate (Approving a Bad Loan)', fontsize=12)
plt.ylabel('True Positive Rate (Catching a Bad Loan)', fontsize=12)
plt.title('ROC Curve: Model Ability to Identify Defaults', fontsize=16, pad=15)
plt.legend(loc="lower right", fontsize=12)
plt.grid(alpha=0.3)

plt.show()

# 1. Create a DataFrame aligning our test data, real financial numbers, and model probabilities
# (Make sure the indexes align with your original X_test)
profit_df = pd.DataFrame({
    'Actual_Class': y_class_test,
    'Model_Prob_Default': y_pred_proba_best, # From your optimized Decision Tree
    'Loan_Amount': X_test['loan_amnt'],      # The raw requested loan amount
    'Actual_Return_Pct': y_reg_test      # This is your ret_PESS column for the test set
})

# 2. Define the thresholds to test
thresholds_to_test = [0.15, 0.20, 0.30, 0.40, 0.50]
profit_results = []

print("--- Total Portfolio Dollar Profit by Threshold ---")

# 3. Loop through thresholds to calculate actual dollars made/lost
for t in thresholds_to_test:
    # Model Decision: If probability >= threshold, Reject (1). Else, Approve (0).
    profit_df['Model_Decision'] = np.where(profit_df['Model_Prob_Default'] >= t, 'Reject', 'Approve')

    # Calculate dollar profit for this specific loan
    # If Approved: Loan Amount * Actual Return Percentage. If Rejected: $0.
    # Corrected: Divide Actual_Return_Pct by 100 to convert percentage to decimal
    profit_df['Dollar_Profit'] = np.where(
        profit_df['Model_Decision'] == 'Approve',
        profit_df['Loan_Amount'] * (profit_df['Actual_Return_Pct'] / 100),
        0
    )

    # Sum the entire portfolio
    total_portfolio_profit = profit_df['Dollar_Profit'].sum()

    # Also calculate how many loans were approved vs rejected for context
    loans_approved = (profit_df['Model_Decision'] == 'Approve').sum()

    profit_results.append({
        'Threshold': f"{t*100}%",
        'Loans Approved': loans_approved,
        'Total Profit ($)': total_portfolio_profit
    })

# 4. Display the results for the client
profit_results_df = pd.DataFrame(profit_results)

# Format the Total Profit column as currency for the client presentation
profit_results_df['Total Profit ($)'] = profit_results_df['Total Profit ($)'].apply(lambda x: f"${x:,.2f}")

display(profit_results_df)

# Extract data for plotting
plot_thresholds = [float(x.strip('%'))/100 for x in profit_results_df['Threshold']]
# We need to re-calculate these from the threshold_results which was previously deleted
# This time we are plotting the financial trade-off for *profit* (loans approved vs. total profit)

# To regenerate these, we need to apply the logic from the qCXjhtaPbhKU cell again or use the existing profit_results_df
# Given profit_results_df has 'Loans Approved' and 'Total Profit ($)' (as strings), we'll parse it.

loans_approved_for_plot = profit_results_df['Loans Approved'].astype(int)
total_profit_for_plot = profit_results_df['Total Profit ($)'].str.replace('$', '', regex=False).str.replace(',', '', regex=False).astype(float)

# Create the plot
fig, ax1 = plt.subplots(figsize=(10, 6))

# Plot 1: Total Profit (The Benefit)
color = 'tab:green'
ax1.set_xlabel('Default Probability Threshold (Stricter ->)', fontsize=12)
ax1.set_ylabel('Total Portfolio Profit ($)', color=color, fontsize=12)
ax1.plot(plot_thresholds, total_profit_for_plot, color=color, marker='o', linewidth=2, label='Total Portfolio Profit')
ax1.tick_params(axis='y', labelcolor=color)
ax1.yaxis.set_major_formatter(plt.FuncFormatter(lambda x, p: f'${x:,.0f}'))

# Create a second y-axis sharing the same x-axis
ax2 = ax1.twinx()

# Plot 2: Number of Loans Approved (The Volume)
color = 'tab:purple'
ax2.set_ylabel('Number of Loans Approved', color=color, fontsize=12)
ax2.plot(plot_thresholds, loans_approved_for_plot, color=color, marker='s', linestyle='--', linewidth=2, label='Number of Loans Approved')
ax2.tick_params(axis='y', labelcolor=color)
ax2.yaxis.set_major_formatter(plt.FuncFormatter(lambda x, p: f'{x:,.0f}'))

# Formatting
plt.title('Business Trade-Off: Profit vs. Loan Volume by Risk Threshold', fontsize=16, pad=15)
fig.tight_layout()
plt.gca().invert_xaxis() # Invert x-axis so stricter thresholds (lower numbers) are on the right
plt.grid(alpha=0.3)
# Add a legend with both lines
lines, labels = ax1.get_legend_handles_labels()
lines2, labels2 = ax2.get_legend_handles_labels()
ax2.legend(lines + lines2, labels + labels2, loc='upper left')
plt.show()

# Set the chosen profit-maximizing threshold from the analysis (30%)
chosen_profit_threshold = 0.30

# Generate final predictions based on this threshold
# We use the y_pred_proba_best from the DecisionTreeClassifier (best_dtc_model) probabilities
final_business_predictions_profit = np.where(y_pred_proba_best >= chosen_profit_threshold, 1, 0)

# Create the Confusion Matrix plot for the profit-maximizing threshold
cm_profit = confusion_matrix(y_class_test, final_business_predictions_profit)
disp_profit = ConfusionMatrixDisplay(confusion_matrix=cm_profit, display_labels=['Will Pay (0)', 'Default (1)'])

fig, ax = plt.subplots(figsize=(8, 6))
disp_profit.plot(cmap='Blues', ax=ax, values_format='d')

plt.title(f'Confusion Matrix at Optimal Profit Threshold ({chosen_profit_threshold*100:.0f}%)', fontsize=16, pad=15)
plt.xlabel('Algorithm Prediction', fontsize=12)
plt.ylabel('Actual Historical Outcome', fontsize=12)
plt.show()

print(f"\nClassification Report at Optimal Profit Threshold ({chosen_profit_threshold*100:.0f}%):")
print(classification_report(y_class_test, final_business_predictions_profit))

from sklearn.tree import plot_tree

plt.figure(figsize=(20, 15)) # Adjust figure size for better visibility
plot_tree(
    best_dtc_model,
    feature_names=X_e.columns.tolist(),
    class_names=['Fully Paid', 'Charged Off'],
    filled=True,
    rounded=True,
    fontsize=10,
    proportion=True,
    impurity=False
)
plt.title('Decision Tree Classifier Visualization', fontsize=20)
plt.show()

"""### LogisticRegression"""

log_reg = LogisticRegression(random_state=42, max_iter=2000, class_weight='balanced')

# Define the hyperparameter grid
log_param_grid = {
    'penalty': ['l1', 'l2'],
    'C': [0.01, 0.1, 1.0, 10.0],
    'solver': ['saga'] # 'saga' handles both L1 and L2 penalties
}

# Setup GridSearchCV
log_grid = GridSearchCV(
    estimator=log_reg,
    param_grid=log_param_grid,
    cv=5,
    scoring='roc_auc',
    n_jobs=-1
    )

print("Training Balanced Logistic Regression...")
log_grid.fit(X_train_scaled, y_class_train)

# Extract the best model
best_log_model = log_grid.best_estimator_
print(f"Best Logistic Regression Params Found: {log_grid.best_params_}")

# Evaluate
y_class_pred_log = best_log_model.predict(X_test_scaled)
y_class_proba_log = best_log_model.predict_proba(X_test_scaled)[:, 1]

print("\n[ Optimized Balanced Logistic Regression Test Performance ]")
print(f"ROC-AUC:           {roc_auc_score(y_class_test, y_class_proba_log):.4f}")
print("-" * 40)
print(f"Accuracy:          {accuracy_score(y_class_test, y_class_pred_log):.4f}")
print(f"Precision:         {precision_score(y_class_test, y_class_pred_log):.4f}")
print(f"Recall:            {recall_score(y_class_test, y_class_pred_log):.4f}")
print(f"F1-Score:          {f1_score(y_class_test, y_class_pred_log):.4f}")
print("=" * 70)

# View the model coefficients
print(f"Intercept: {best_log_model.intercept_[0]:.4f}")

# Create a DataFrame of coefficients sorted by magnitude
coef_df = pd.DataFrame({
    'Feature': X_train.columns,
    'Coefficient': best_log_model.coef_[0]
}).sort_values('Coefficient', key=abs, ascending=False)

print("Top 10 Coefficients (by absolute magnitude):")
print(coef_df.head(10).to_string(index=False))

"""After understanding the coefficients, we should visualize the model's performance with a confusion matrix and an ROC curve, similar to what we did for the Decision Tree Classifier. This will help us compare the models more effectively."""

# Confusion Matrix for Logistic Regression
cm_log_reg = confusion_matrix(y_class_test, y_class_pred_log)
disp_log_reg = ConfusionMatrixDisplay(confusion_matrix=cm_log_reg, display_labels=['Fully Paid (0)', 'Charged Off (1)'])

fig, ax = plt.subplots(figsize=(8, 6))
disp_log_reg.plot(cmap='Blues', ax=ax, values_format='d')
plt.title('Confusion Matrix for Logistic Regression', fontsize=16, pad=15)
plt.xlabel('Predicted Label', fontsize=12)
plt.ylabel('True Label', fontsize=12)
plt.show()

# ROC Curve for Logistic Regression
fpr_log, tpr_log, thresholds_log = roc_curve(y_class_test, y_class_proba_log)
auc_log = roc_auc_score(y_class_test, y_class_proba_log)

plt.figure(figsize=(8, 6))
plt.plot(fpr_log, tpr_log, color='red', lw=2, label=f'Logistic Regression (AUC = {auc_log:.3f})')
plt.plot([0, 1], [0, 1], color='gray', lw=2, linestyle='--', label='Random Guessing (AUC = 0.500)')

plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('False Positive Rate', fontsize=12)
plt.ylabel('True Positive Rate', fontsize=12)
plt.title('ROC Curve: Logistic Regression', fontsize=16, pad=15)
plt.legend(loc="lower right", fontsize=12)
plt.grid(alpha=0.3)
plt.show()

# Classification Report for Logistic Regression
print("\nClassification Report for Logistic Regression:")
print(classification_report(y_class_test, y_class_pred_log, target_names=['Fully Paid', 'Charged Off']))

# Plotting both ROC Curves for Comparison
plt.figure(figsize=(10, 8))

# Recompute fpr and tpr for Decision Tree Classifier to ensure correct dimensions
# y_class_test and y_pred_proba_best are available from previous cells (e.g., KrbDt7r2JHF5)
fpr, tpr, _ = roc_curve(y_class_test, y_pred_proba_best)

# Decision Tree Classifier ROC
plt.plot(fpr, tpr, color='blue', lw=2, label=f'Decision Tree (AUC = {test_auc:.3f})')

# Logistic Regression ROC
plt.plot(fpr_log, tpr_log, color='red', lw=2, label=f'Logistic Regression (AUC = {auc_log:.3f})')

plt.plot([0, 1], [0, 1], color='gray', lw=2, linestyle='--', label='Random Guessing (AUC = 0.500)')

plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('False Positive Rate', fontsize=12)
plt.ylabel('True Positive Rate', fontsize=12)
plt.title('ROC Curve Comparison: Decision Tree vs. Logistic Regression', fontsize=16, pad=15)
plt.legend(loc="lower right", fontsize=12)
plt.grid(alpha=0.3)
plt.show()

fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(16, 6))

# Confusion Matrix for Decision Tree Classifier (using Optimal Profit Threshold)
disp_dtc = ConfusionMatrixDisplay(confusion_matrix=cm_profit, display_labels=['Fully Paid (0)', 'Charged Off (1)'])
disp_dtc.plot(cmap='Blues', ax=ax1, values_format='d')
ax1.set_title('DTC Confusion Matrix (Optimal Profit Thresh)', fontsize=14)
ax1.set_xlabel('Predicted Label', fontsize=12)
ax1.set_ylabel('True Label', fontsize=12)

# Confusion Matrix for Logistic Regression
disp_log_reg = ConfusionMatrixDisplay(confusion_matrix=cm_log_reg, display_labels=['Fully Paid (0)', 'Charged Off (1)'])
disp_log_reg.plot(cmap='Blues', ax=ax2, values_format='d')
ax2.set_title('LogReg Confusion Matrix (Balanced Weights)', fontsize=14)
ax2.set_xlabel('Predicted Label', fontsize=12)
ax2.set_ylabel('True Label', fontsize=12)

plt.tight_layout()
plt.show()

"""Now that we have both ROC curves plotted together, let's discuss how to interpret them and combine this with the detailed metrics to make an informed decision for your client.

Comparing DTC vs. Logistic Regression for Client Use:

1.  **ROC-AUC Score:**
    *   **Logistic Regression (AUC: ~0.713)** generally has a slightly higher AUC than the **Decision Tree (AUC: ~0.697)**. A higher AUC indicates better overall discriminative power, meaning the model is better at distinguishing between defaulting and non-defaulting loans across various thresholds.

2.  **Recall vs. Precision Trade-off (from Classification Reports):**
    *   **Decision Tree:** Showed very high specificity (good at identifying 'Fully Paid' loans) but very low recall for 'Charged Off' loans (missed many actual defaults). This means it's very conservative, approving most loans but failing to flag many bad ones.
    *   **Logistic Regression (Balanced):** Demonstrated much higher recall for 'Charged Off' loans (better at catching defaults) at the cost of lower precision (more false alarms, i.e., incorrectly flagging good loans as bad). This model is more aggressive in identifying potential defaults.

3.  **Business Objectives:**
    *   **If minimizing losses from defaults is paramount (risk aversion):** A model with higher recall for the 'Charged Off' class (like the Logistic Regression with balanced weights) might be preferred, even if it means rejecting some good loans (more false positives). The priority here is to *not* lend to a defaulting client.
    *   **If maximizing loan approvals and avoiding rejecting good clients is paramount (revenue focus):** A model with higher precision for 'Charged Off' and higher specificity (low False Positive Rate) might be preferred. The Decision Tree, despite its low recall, has a very low FPR, meaning it rarely rejects a good loan. However, its extremely low recall for 'Charged Off' is a major drawback.
    *   **Balancing both:** The ROC curve helps visualize this trade-off. You can choose a threshold that balances these concerns based on where your client wants to operate on the curve.

4.  **Interpretability:**
    *   **Decision Tree:** Can be highly interpretable if the `max_depth` is kept small, allowing you to see the exact rules the model uses. (We visualized this previously).
    *   **Logistic Regression:** The coefficients indicate the direction and strength of the relationship between features and the log-odds of default, offering good interpretability (as we saw with the coefficients). For example, a positive coefficient means that feature increases the likelihood of default.

Next Steps:

Based on this comparison, we can discuss with your client:
*   What is their primary business objective? Is it risk mitigation (minimizing defaults) or revenue generation (maximizing approvals)?
*   What is the acceptable balance between catching defaults (recall) and avoiding falsely rejecting good applicants (precision/FPR)?

Once these business priorities are clearer, we can make an informed decision on which model, or even which threshold for a given model, is most appropriate.

### DecisionTreeRegressor
"""

# Define a parameter grid for DecisionTreeRegressor
dt_reg_param_grid = {
    'max_depth': [3, 5, 7, 10, None], # None means unlimited depth
    'min_samples_split': [2, 5, 10, 20],
    'min_samples_leaf': [1, 5, 10, 20],
    'random_state': [42]
}

# Initialize the base Decision Tree Regressor model
dtr_base = DecisionTreeRegressor(random_state=42)

# Setup GridSearchCV
# We'll use 'neg_mean_squared_error' for scoring, as GridSearchCV minimizes this value.
# The best model will have the smallest (least negative) MSE, corresponding to the lowest RMSE.
grid_search_dtr = GridSearchCV(estimator=dtr_base,
                               param_grid=dt_reg_param_grid,
                               cv=5,
                               scoring='neg_mean_squared_error',
                               verbose=1,
                               n_jobs=-1)

print("GridSearchCV for Decision Tree Regressor successfully initialized!")

# Run the Grid Search (This might take some time)
print("Training Decision Tree Regressor...")
grid_search_dtr.fit(X_train_scaled, y_reg_train)

# Extract the best model
best_dtr_model = grid_search_dtr.best_estimator_

# Display the winning parameters
print("\n--- Grid Search Complete for Decision Tree Regressor ---")
print("Best Hyperparameters Found:")
for param, value in grid_search_dtr.best_params_.items():
    print(f" - {param}: {value}")

# Convert negative MSE to RMSE for easier interpretation
best_rmse = np.sqrt(-grid_search_dtr.best_score_)
print(f"\nBest Cross-Validation RMSE: {best_rmse:.3f}")

# Predict on the scaled test set using the best DTR model
y_reg_pred_dtr = best_dtr_model.predict(X_test_scaled)

# Evaluate the model's performance
rmse_dtr = np.sqrt(mean_squared_error(y_reg_test, y_reg_pred_dtr))
mae_dtr = mean_absolute_error(y_reg_test, y_reg_pred_dtr)
r2_dtr = r2_score(y_reg_test, y_reg_pred_dtr)

print("--- Decision Tree Regressor Test Performance ---")
print(f"RMSE:      {rmse_dtr:.4f}")
print(f"MAE:       {mae_dtr:.4f}")
print(f"R-Squared: {r2_dtr:.4f}")
print("=" * 50)

"""##### Decision Tree Regressor Visualizations"""

from sklearn.tree import plot_tree
import matplotlib.pyplot as plt

plt.figure(figsize=(30, 20)) # Adjust figure size for better visibility
plot_tree(
    best_dtr_model,
    feature_names=X_e.columns.tolist(),
    filled=True,
    rounded=True,
    fontsize=8,
    proportion=False, # Set to False for actual sample counts/values
    impurity=True # Show impurity for regression trees
)
plt.title('Decision Tree Regressor Visualization (Max Depth 5)', fontsize=20)
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

# 1. Actual vs. Predicted Values Plot
plt.figure(figsize=(10, 6))
sns.regplot(x=y_reg_test, y=y_reg_pred_dtr, scatter_kws={'alpha':0.3}, line_kws={'color':'red'})
plt.title('DT Regressor: Actual vs. Predicted ret_PESS', fontsize=16)
plt.xlabel('Actual ret_PESS', fontsize=12)
plt.ylabel('Predicted ret_PESS', fontsize=12)
plt.grid(True, linestyle='--', alpha=0.6)
plt.axline((0, 0), slope=1, color='gray', linestyle='--', label='Perfect Prediction') # Add a y=x line
plt.legend()
plt.show()

"""This plot shows how closely the model's predictions align with the actual loan returns. Ideally, points would cluster tightly around the red regression line and the gray 'perfect prediction' line. The wider spread here confirms the low R-squared, indicating the model struggles to predict `ret_PESS` accurately."""

# 2. Residuals Plot (Errors)
residuals = y_reg_test - y_reg_pred_dtr

plt.figure(figsize=(10, 6))
sns.scatterplot(x=y_reg_pred_dtr, y=residuals, alpha=0.3)
plt.axhline(y=0, color='red', linestyle='--', label='Zero Residuals')
plt.title('DT Regressor: Residuals Plot', fontsize=16)
plt.xlabel('Predicted ret_PESS', fontsize=12)
plt.ylabel('Residuals (Actual - Predicted)', fontsize=12)
plt.grid(True, linestyle='--', alpha=0.6)
plt.legend()
plt.show()

"""The residuals plot helps us identify patterns in the errors. For a good model, residuals should be randomly scattered around zero. Here, the wide spread indicates that the model's errors are substantial and don't show a clear pattern of bias (like consistently over- or under-predicting at certain values), but rather a general lack of predictive power."""

# 3. Feature Importance Plot

# Ensure feature names match the scaled data used for training
feature_names = X_e.columns.tolist() # X_e was used before scaling to get column names
importances = best_dtr_model.feature_importances_

# Create a DataFrame for better visualization
feature_importance_df = pd.DataFrame({
    'Feature': feature_names,
    'Importance': importances
}).sort_values(by='Importance', ascending=False)

plt.figure(figsize=(12, 7))
sns.barplot(x='Importance', y='Feature', data=feature_importance_df.head(15), palette='viridis')
plt.title('DT Regressor: Top 15 Feature Importances', fontsize=16)
plt.xlabel('Relative Importance', fontsize=12)
plt.ylabel('Feature', fontsize=12)
plt.grid(axis='x', linestyle='--', alpha=0.6)
plt.tight_layout()
plt.show()

"""This bar chart displays the most important features that the Decision Tree Regressor used to make its predictions. Features higher up the list contributed more to the model's decisions. This helps in understanding which aspects of a loan application were most influential in predicting the `ret_PESS`."""

# 4. Distribution of Residuals

plt.figure(figsize=(10, 6))
sns.histplot(residuals, kde=True, bins=50, color='skyblue')
plt.axvline(x=0, color='red', linestyle='--', label='Zero Residual')
plt.title('DT Regressor: Distribution of Residuals', fontsize=16)
plt.xlabel('Residual Value (Actual - Predicted)', fontsize=12)
plt.ylabel('Frequency', fontsize=12)
plt.legend()
plt.grid(axis='y', linestyle='--', alpha=0.6)
plt.show()

"""### Visualizing the Decision Tree Structure

For interpretability, you could also visualize the actual decision tree using `sklearn.tree.plot_tree`. However, with a `max_depth` of 5 (as chosen for our best model), the tree can still be quite large and difficult to view clearly on a standard plot.

If you want to explore the exact rules, you would typically:
1.  **Adjust `max_depth` to a very small number (e.g., 2 or 3) during training** to get a highly simplified tree.
2.  Then, use `plot_tree(best_dtr_model, feature_names=X_e.columns.tolist(), filled=True, rounded=True)` to visualize it. This would show the exact splits and criteria at each node, making it transparent for the client.

### LinearRegression
"""

# 1. Generate Polynomial Features
poly_transformer = PolynomialFeatures(degree=2, include_bias=False)
X_train_poly = poly_transformer.fit_transform(X_train_scaled)
X_test_poly = poly_transformer.transform(X_test_scaled)

print(f"Original features: {X_train_scaled.shape[1]}")
print(f"Polynomial features (train): {X_train_poly.shape[1]}")
print(f"Polynomial features (test): {X_test_poly.shape[1]}")

# 2. Train LassoCV directly on the polynomial features
print("Training LassoCV on polynomial features...")
lasso_cv_model_no_pipe = LassoCV(cv=5, random_state=42, max_iter=10000, n_jobs=-1)
lasso_cv_model_no_pipe.fit(X_train_poly, y_reg_train)

best_alpha_no_pipe = lasso_cv_model_no_pipe.alpha_
print(f"Best Alpha (Penalty) Found (no pipeline): {best_alpha_no_pipe:.4f}")

# 3. Predict on the transformed TEST set
y_reg_pred_poly_no_pipe = lasso_cv_model_no_pipe.predict(X_test_poly)

# 4. Evaluate the model
rmse_poly_no_pipe = np.sqrt(mean_squared_error(y_reg_test, y_reg_pred_poly_no_pipe))
mae_poly_no_pipe = mean_absolute_error(y_reg_test, y_reg_pred_poly_no_pipe)
r2_poly_no_pipe = r2_score(y_reg_test, y_reg_pred_poly_no_pipe)

print("\n[ Optimized Poly-Lasso Regression Test Performance (no pipeline) ]")
print(f"RMSE:      {rmse_poly_no_pipe:.4f}")
print(f"MAE:       {mae_poly_no_pipe:.4f}")
print(f"R-Squared: {r2_poly_no_pipe:.4f}")
print("-" * 70)

### Polynomial LassoCV Regression Visualizations

"""#### 1. Actual vs. Predicted `ret_PESS`

This plot helps us understand how well the model's predictions for `ret_PESS` (Return on Investment, which is our target variable) align with the actual observed `ret_PESS` values.

*   **Red Line (Regression Line):** Shows the general trend of our model's predictions relative to actual values. Ideally, this line would be close to the gray dashed line.
*   **Gray Dashed Line (Perfect Prediction):** Represents a scenario where the model predicts perfectly (predicted value equals actual value).

Points clustered tightly around the gray line indicate accurate predictions. A wide spread of points suggests the model has difficulty accurately predicting the exact `ret_PESS` for individual loans. In our case, the spread indicates that while the model captures some general trend, it struggles with precise individual predictions, as reflected in the low R-squared score.
"""

import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# 1. Actual vs. Predicted Values Plot
plt.figure(figsize=(10, 6))
sns.regplot(x=y_reg_test, y=y_reg_pred_poly_no_pipe, scatter_kws={'alpha':0.3}, line_kws={'color':'red'})
plt.title('Poly LassoCV Regressor: Actual vs. Predicted ret_PESS', fontsize=16)
plt.xlabel('Actual ret_PESS', fontsize=12)
plt.ylabel('Predicted ret_PESS', fontsize=12)
plt.grid(True, linestyle='--', alpha=0.6)
plt.axline((0, 0), slope=1, color='gray', linestyle='--', label='Perfect Prediction') # Add a y=x line
plt.legend()
plt.show()

"""#### 2. Residuals Plot

The residuals plot visualizes the errors (differences between actual and predicted values) made by our model.

*   **X-axis (Predicted `ret_PESS`):** The model's predicted values.
*   **Y-axis (Residuals):** The error for each prediction (`Actual ret_PESS` - `Predicted ret_PESS`).
*   **Red Dashed Line (Zero Residuals):** Represents perfect predictions where the error is zero.

For a good regression model, we expect to see a random scatter of points around the zero line, with no discernible patterns (like a cone shape, a curve, or increasing/decreasing variance). A random scatter indicates that the model's errors are consistent across the range of predictions. The wide spread here indicates the model's predictions have significant errors, confirming the low predictive power.
"""

# 2. Residuals Plot (Errors)
residuals_poly_no_pipe = y_reg_test - y_reg_pred_poly_no_pipe

plt.figure(figsize=(10, 6))
sns.scatterplot(x=y_reg_pred_poly_no_pipe, y=residuals_poly_no_pipe, alpha=0.3)
plt.axhline(y=0, color='red', linestyle='--', label='Zero Residuals')
plt.title('Poly LassoCV Regressor: Residuals Plot', fontsize=16)
plt.xlabel('Predicted ret_PESS', fontsize=12)
plt.ylabel('Residuals (Actual - Predicted)', fontsize=12)
plt.grid(True, linestyle='--', alpha=0.6)
plt.legend()
plt.show()

"""#### 3. Distribution of Residuals

This histogram shows the frequency distribution of our model's errors.

*   **X-axis (Residual Value):** The size of the error.
*   **Y-axis (Frequency):** How often each error size occurs.
*   **Red Dashed Line (Zero Residual):** Indicates where perfect predictions would fall.

Ideally, for a well-performing model, the residuals should be normally distributed around zero (forming a bell curve centered at zero). A skewed or non-normal distribution, or one not centered at zero, suggests potential biases or systematic errors in the model. Here, the distribution is somewhat centered around zero, but its wide spread reinforces that the magnitude of errors can be large.
"""

# 3. Distribution of Residuals
plt.figure(figsize=(10, 6))
sns.histplot(residuals_poly_no_pipe, kde=True, bins=50, color='skyblue')
plt.axvline(x=0, color='red', linestyle='--', label='Zero Residual')
plt.title('Poly LassoCV Regressor: Distribution of Residuals', fontsize=16)
plt.xlabel('Residual Value (Actual - Predicted)', fontsize=12)
plt.ylabel('Frequency', fontsize=12)
plt.legend()
plt.grid(axis='y', linestyle='--', alpha=0.6)
plt.show()

"""#### 4. Top 20 Feature Coefficients

For linear models like Lasso Regression, coefficients indicate the strength and direction of the relationship between each feature and the target variable (`ret_PESS`). This plot shows the features that the model found most influential.

*   **Positive Coefficient:** As the feature value increases, `ret_PESS` is predicted to increase.
*   **Negative Coefficient:** As the feature value increases, `ret_PESS` is predicted to decrease.
*   **Magnitude:** Larger absolute coefficient values indicate a stronger influence on the prediction. Polynomial features (e.g., `int_rate^2` or interaction terms like `int_rate grade_B`) capture non-linear relationships and how features combine.

This helps us understand which loan application characteristics the model prioritizes when predicting the potential return.
"""

# 3. Display Coefficients (already generated, but will include here for completeness and context)
# Get the feature names after polynomial transformation
poly_feature_names_no_pipe = poly_transformer.get_feature_names_out(X_e.columns)

# Create a DataFrame of coefficients
coef_df_poly_no_pipe = pd.DataFrame({
    'Feature': poly_feature_names_no_pipe,
    'Coefficient': lasso_cv_model_no_pipe.coef_
}).sort_values(by='Coefficient', key=abs, ascending=False)

# Plotting coefficients
plt.figure(figsize=(12, 8))
sns.barplot(x='Coefficient', y='Feature', data=coef_df_poly_no_pipe.head(20), palette='coolwarm')
plt.title('Top 20 Coefficients: Polynomial LassoCV Regression', fontsize=16)
plt.xlabel('Coefficient Value', fontsize=12)
plt.ylabel('Feature', fontsize=12)
plt.grid(axis='x', linestyle='--', alpha=0.6)
plt.tight_layout()
plt.show()

# 3. Display Coefficients
# Get the feature names after polynomial transformation
poly_feature_names_no_pipe = poly_transformer.get_feature_names_out(X_e.columns)

# Create a DataFrame of coefficients
coef_df_poly_no_pipe = pd.DataFrame({
    'Feature': poly_feature_names_no_pipe,
    'Coefficient': lasso_cv_model_no_pipe.coef_
}).sort_values(by='Coefficient', key=abs, ascending=False)

print("Top 20 Coefficients (by absolute magnitude) for Polynomial LassoCV Regression (no pipeline):")
print(coef_df_poly_no_pipe.head(20).to_string(index=False))



import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# --- 1. Combined Actual vs. Predicted Plot ---
plt.figure(figsize=(12, 7))
sns.regplot(x=y_reg_test, y=y_reg_pred_dtr, scatter_kws={'alpha':0.2}, line_kws={'color':'blue', 'label':'DTR Regression Line'})
sns.regplot(x=y_reg_test, y=y_reg_pred_poly_no_pipe, scatter_kws={'alpha':0.2}, line_kws={'color':'red', 'label':'Poly LassoCV Regression Line'})
plt.axline((y_reg_test.min(), y_reg_test.min()), slope=1, color='gray', linestyle='--', label='Perfect Prediction')
plt.title('Actual vs. Predicted ret_PESS: DTR vs. Poly LassoCV', fontsize=16)
plt.xlabel('Actual ret_PESS', fontsize=12)
plt.ylabel('Predicted ret_PESS', fontsize=12)
plt.grid(True, linestyle='--', alpha=0.6)
plt.legend()
plt.show()

# --- 2. Combined Residuals Plot ---
residuals_dtr = y_reg_test - y_reg_pred_dtr
residuals_poly_no_pipe = y_reg_test - y_reg_pred_poly_no_pipe

plt.figure(figsize=(12, 7))
sns.scatterplot(x=y_reg_pred_dtr, y=residuals_dtr, alpha=0.2, color='blue', label='DTR Residuals')
sns.scatterplot(x=y_reg_pred_poly_no_pipe, y=residuals_poly_no_pipe, alpha=0.2, color='red', label='Poly LassoCV Residuals')
plt.axhline(y=0, color='gray', linestyle='--', label='Zero Residuals')
plt.title('Residuals Plot: DTR vs. Poly LassoCV', fontsize=16)
plt.xlabel('Predicted ret_PESS', fontsize=12)
plt.ylabel('Residuals (Actual - Predicted)', fontsize=12)
plt.grid(True, linestyle='--', alpha=0.6)
plt.legend()
plt.show()

# --- 3. Combined Residuals Distribution Plot ---
fig, axes = plt.subplots(1, 2, figsize=(15, 6), sharey=True)

sns.histplot(residuals_dtr, kde=True, bins=50, color='blue', ax=axes[0])
axes[0].axvline(x=0, color='red', linestyle='--', label='Zero Residual')
axes[0].set_title('DTR: Distribution of Residuals', fontsize=14)
axes[0].set_xlabel('Residual Value', fontsize=12)
axes[0].set_ylabel('Frequency', fontsize=12)
axes[0].legend()
axes[0].grid(axis='y', linestyle='--', alpha=0.6)

sns.histplot(residuals_poly_no_pipe, kde=True, bins=50, color='red', ax=axes[1])
axes[1].axvline(x=0, color='blue', linestyle='--', label='Zero Residual')
axes[1].set_title('Poly LassoCV: Distribution of Residuals', fontsize=14)
axes[1].set_xlabel('Residual Value', fontsize=12)
axes[1].set_ylabel('Frequency', fontsize=12)
axes[1].legend()
axes[1].grid(axis='y', linestyle='--', alpha=0.6)

plt.tight_layout()
plt.show()

# --- 4. Performance Metrics Bar Chart ---
# Retrieve metrics from kernel state or re-calculate if necessary
# (Assuming these variables are already defined in the kernel state)
# rmse_dtr, mae_dtr, r2_dtr for Decision Tree Regressor
# np.sqrt(mean_squared_error(y_reg_test, y_reg_pred_poly)),
# mean_absolute_error(y_reg_test, y_reg_pred_poly),
# r2_score(y_reg_test, y_reg_pred_poly) for Poly LassoCV

metrics_data = {
    'Metric': ['RMSE', 'MAE', 'R-squared'],
    'DTR': [rmse_dtr, mae_dtr, r2_dtr],
    'Poly LassoCV': [rmse_poly_no_pipe, mae_poly_no_pipe, r2_poly_no_pipe]
}

metrics_df = pd.DataFrame(metrics_data)
metrics_df_melted = metrics_df.melt('Metric', var_name='Model', value_name='Score')

plt.figure(figsize=(10, 6))
sns.barplot(x='Metric', y='Score', hue='Model', data=metrics_df_melted, palette={'DTR': 'blue', 'Poly LassoCV': 'red'})
plt.title('Comparison of Regression Model Performance Metrics', fontsize=16)
plt.xlabel('Metric', fontsize=12)
plt.ylabel('Score Value', fontsize=12)
plt.grid(axis='y', linestyle='--', alpha=0.6)
plt.show()