# -*- coding: utf-8 -*-
"""main

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u7UaTt2fjtW4iDsHxpQS-ZZNyqOLkSWX
"""

import streamlit as st
import pandas as pd
import numpy as np
import joblib

# --- 1. CONFIGURATION & BUSINESS RULES ---
st.set_page_config(page_title="Bucknell Lending Club - Loan Risk & Return Simulator", page_icon=" Bison_emoji:", layout="wide")
PROFIT_THRESHOLD = 0.30

# --- Custom Bucknell Theme (Navy Blue and Orange) ---
st.markdown(
    """
    <style>
    /* Main background color */
    .stApp {
        background-color: #f0f2f6; /* A light grey for overall app background */
    }
    /* Sidebar and other secondary backgrounds */
    .css-1d391kg, .css-1dp5vir { /* Targeting sidebar and main content blocks */
        background-color: #193153; /* Bucknell Navy Blue for prominent areas */
        color: white;
    }
    /* Primary accent color (buttons, sliders, etc.) */
    .stButton>button, .stSlider>.st-da, .stTextInput>div>div>input:focus {
        background-color: #C63300; /* Bucknell Orange */
        color: white;
        border-color: #C63300;
    }
    .stButton>button:hover {
        background-color: #E04400; /* Slightly lighter orange on hover */
        border-color: #E04400;
    }
    /* Text color for main content */
    .st-emotion-cache-nahz7x, .st-emotion-cache-nahz7x p {
        color: #193153; /* Darker text for readability */
    }
    /* Header and subheader colors */
    h1, h2, h3, h4, h5, h6 {
        color: #C63300; /* Bucknell Orange for headers */
    }
    /* Labels for input widgets */
    .st-emotion-cache-gh2jqy {
        color: #193153; /* Navy for input labels */
    }
    </style>
    """,
    unsafe_allow_html=True
)

# Remove poly_lasso_pipe and add these two:
@st.cache_resource
def load_artifacts():
    dtc_model = joblib.load('dtc_model.pkl')

    # Load the separated regression pieces
    poly_maker = joblib.load('poly_maker.pkl')
    lasso_model = joblib.load('lasso_model.pkl')

    scaler_class = joblib.load('scaler.pkl')
    expected_cols_class = joblib.load('expected_columns.pkl')
    scaler_poly = joblib.load('scaler_poly.pkl')
    expected_cols_poly = joblib.load('expected_columns_poly.pkl')

    return dtc_model, poly_maker, lasso_model, scaler_class, expected_cols_class, scaler_poly, expected_cols_poly

dtc_model, poly_maker, lasso_model, scaler_class, expected_cols_class, scaler_poly, expected_cols_poly = load_artifacts()

# --- 3. UI: APP HEADER ---
st.title("🏦 Institutional Loan Risk Dashboard")
st.markdown("Enter the applicant's financial details below to simulate the probability of default and projected return.")
st.divider()

# --- 4. UI: DATA INPUT LAYOUT ---
# Using columns to make the form look like a professional dashboard
col1, col2, col3 = st.columns(3)

with col1:
    st.subheader("Loan Details")
    loan_amnt = st.number_input("Loan Amount ($)", min_value=500, max_value=40000, value=10000, step=500)
    term_num = st.selectbox("Term (Months)", options=[36, 60])
    int_rate = st.number_input("Interest Rate (%)", min_value=5.0, max_value=35.0, value=12.0, step=0.1)
    grade = st.selectbox("Lending Club Grade", options=['A', 'B', 'C', 'D', 'E', 'F', 'G'])
    purpose = st.selectbox("Purpose", options=['debt_consolidation', 'credit_card', 'home_improvement', 'other', 'major_purchase', 'small_business'])

with col2:
    st.subheader("Applicant Profile")
    annual_inc = st.number_input("Annual Income ($)", min_value=0, max_value=1000000, value=60000, step=1000)
    emp_length = st.selectbox("Employment Length", options=['< 1 year', '1 year', '2 years', '3 years', '4 years', '5 years', '6 years', '7 years', '8 years', '9 years', '10+ years'])
    home_ownership = st.selectbox("Home Ownership", options=['RENT', 'OWN', 'MORTGAGE', 'ANY'])
    verification_status = st.selectbox("Income Verification", options=['Not Verified', 'Source Verified', 'Verified'])
    dti = st.number_input("Debt-to-Income Ratio (DTI)", min_value=0.0, max_value=100.0, value=15.0, step=0.1)

with col3:
    st.subheader("Credit History")
    fico_range_high = st.number_input("FICO Score (High)", min_value=300, max_value=850, value=700, step=5)
    open_acc = st.number_input("Open Credit Lines", min_value=0, max_value=100, value=10, step=1)
    revol_bal = st.number_input("Revolving Balance ($)", min_value=0, max_value=500000, value=15000, step=500)
    revol_util = st.number_input("Revolving Utilization (%)", min_value=0.0, max_value=200.0, value=50.0, step=1.0)
    pub_rec = st.number_input("Public Records (Derogatory)", min_value=0, max_value=50, value=0, step=1)
    delinq_2yrs = st.number_input("Delinquencies (Past 2 Yrs)", min_value=0, max_value=50, value=0, step=1)

# --- 5. EXECUTE PREDICTION ---
st.divider()
if st.button("Run Risk Simulation", type="primary", use_container_width=True):

    # A. Package inputs into a DataFrame exactly as the model expects
    input_data = {
        'loan_amnt': loan_amnt,
        'term_num': term_num,
        'int_rate': int_rate,
        'grade': grade,
        'emp_length': emp_length,
        'home_ownership': home_ownership,
        'annual_inc': annual_inc,
        'verification_status': verification_status,
        'purpose': purpose,
        'dti': dti,
        'fico_range_high': fico_range_high,
        'open_acc': open_acc,
        'pub_rec': pub_rec,
        'delinq_2yrs': delinq_2yrs,
        'revol_bal': revol_bal,
        'revol_util': revol_util
    }

    raw_df = pd.DataFrame([input_data])

    # B. Feature Engineering
    raw_df['annual_inc_log'] = np.log1p(raw_df['annual_inc'])
    raw_df = raw_df.drop('annual_inc', axis=1)

    categorical_cols = raw_df.select_dtypes(include=['object']).columns.tolist()
    encoded_df = pd.get_dummies(raw_df, columns=categorical_cols)

    # C. Align columns for the Classifier
    # Reindex ensures the incoming dummy columns perfectly match the training columns. Missing columns get filled with 0.
    aligned_class_df = encoded_df.reindex(columns=expected_cols_class, fill_value=0)
    scaled_class_X = scaler_class.transform(aligned_class_df)

    # D. Align columns for the Regressor
    aligned_poly_df = encoded_df.reindex(columns=expected_cols_poly, fill_value=0)
    scaled_poly_X = scaler_poly.transform(aligned_poly_df)

    # E. Make Predictions
    prob_default = dtc_model.predict_proba(scaled_class_X)[0][1]

    poly_features = poly_maker.transform(scaled_poly_X)

    est_return = lasso_model.predict(poly_features)[0]

    # F. Business Logic
    if prob_default >= PROFIT_THRESHOLD:
        decision = "REJECT"
        decision_color = "red"
    else:
        decision = "APPROVE"
        decision_color = "green"

    # --- 6. DISPLAY RESULTS ---
    st.header("Simulation Results")

    res_col1, res_col2, res_col3 = st.columns(3)

    with res_col1:
        st.metric(label="Probability of Default", value=f"{prob_default * 100:.2f}%")

    with res_col2:
        st.metric(label="Estimated Return (PESS)", value=f"{est_return:.2f}%")

    with res_col3:
        st.markdown(f"### Decision: <span style='color:{decision_color}'>{decision}</span>", unsafe_allow_html=True)
        st.caption(f"Based on max risk threshold of {PROFIT_THRESHOLD * 100}%")
